### ISSUE TITLE
New requirements

### ISSUE THREAD

**Issue by ozanbulut** [bounswe/bounswe2016group5#21]
After presentation, Suzan hoca requested new feature about hierarchy on topics. Although we talked with Cihat after that, she said after updating requirements you should see me to. 

We should update requirements, she will probably want to see it in next lecture.

**Comment by seymaertem** [comment]
Should i include these requirements in the requirement page? Do you think we should add smth more?

Relationship Requirements
- Each topic page shall have a related topic section. Topic owner shall be able to add topics which are related to the topic.
- Topic owner shall be able to distinguish some topics as suggested prerequisites.
