### ISSUE TITLE
Google Drive Folder Creation

### ISSUE THREAD

**Issue by suyunu** [bounswe/bounswe2016group5#3]
A folder on Google Drive will be created for large sized file sharing.

**Comment by gokarslan** [comment]
I shared google drive folder. @sevdacopur @mbugc can you send your e-mail addresses to me?

**Comment by sevdacopur** [comment]
sevdacopur019@gmail.com
18 Şub 2016 14:21 tarihinde "Kerim Gokarslan" notifications@github.com
yazdı:

**Comment by mbugc** [comment]
Mustafa.bugra.cil@gmail.com

18 Şubat 2016 Perşembe tarihinde, sevdacopur notifications@github.com
yazdı:
