### ISSUE TITLE
Homework-2-Part B-remainder

### ISSUE THREAD

**Issue by atakanguney** [bounswe/bounswe2016group5#4]
Explore related material on team work, communication, lifecycles, good practices & bad practices. Put references and comments about your findings on your project repository.

@gokarslan @sevdacopur @sevdacopur @dabager @ozerbiber  @mbugc

**Comment by suyunu** [comment]
- [x] [Team Work & Communication](https://github.com/bounswe/bounswe2016group5/wiki/Teamwork)
- [X] [Lifecycles](https://github.com/bounswe/bounswe2016group5/wiki/Software-Development-Life-Cycle)
- [X] [Good & Bad Practices](https://github.com/bounswe/bounswe2016group5/wiki/Good-&-Bad-Practices)
