### ISSUE TITLE
Assignment-2

### ISSUE THREAD

**Issue by atakanguney** [bounswe/bounswe2016group5#5]
Each member should write at least 5 user stories with non-trivial acceptance criteria. 
        About user stories with acceptance criteria: see [this page](http://www.boost.co.nz/blog/2010/09/acceptance-criteria/) and [here](http://nomad8.com/acceptance_criteria/) is another explanation.

Each member should write 1-2 persona.

And domain analysis.
@gokarslan @sevdacopur @suyunu @mbugc @dabager @ozerbiber

**Comment by gokarslan** [comment]
did we agree on themes/features?

**Comment by atakanguney** [comment]
I think we should write user stories first , so we can decide what themes/features we will have.

**Comment by dabager** [comment]
I added my user stories and a theme in Google Drive folder. You can check it out.

**Comment by atakanguney** [comment]
Ok. I added my stories and themes also in same folder.

**Comment by gokarslan** [comment]
I also added my stories, persona and domain analysis. I named 3 different files for stories, personas and domain analysis.

**Comment by mbugc** [comment]
I will add them before 7.30.

7 Mart 2016 Pazartesi tarihinde, Kerim Gokarslan notifications@github.com
yazdı:

**Comment by sevdacopur** [comment]
I added my domain analysis and will add others in 20 minutes.

**Comment by mbugc** [comment]
I added all of it.

**Comment by mbugc** [comment]
Everything looks fine, any additional comments?

**Comment by suyunu** [comment]
I've also added some user stories and themes.

I think user stories and features look fine but we should organize and add something more to Domain Analysis like comparision with our project and benefits of our project etc.

**Comment by gokarslan** [comment]
I think everything is fine, I think we can close this issue.
And thank you all for participating.
