### ISSUE TITLE
Search Mechanism

### ISSUE THREAD

**Issue by mbugc** [bounswe/bounswe2016group5#52]
Search should be like this :

If user types something and clicks search->

text would be searched throught topics, if some topic header matches even partially return first 3 topics.

text would be searched through tag-entity table, if some tag_text matches, return 3 topics of that tag.
and pick first 4 related entities and search through tag-entity table, if some entity_text matches, return a topic of that entity.

This way we will return 10 topics.

**Comment by gokarslan** [comment]
creating tag with entities and the searching algorithm is implemented, testing needed.
